<a href="https://colab.research.google.com/github/rohulfahad/skill-morph/blob/Assignment-5/Assignment_5_Data_Preprocessing_and_Pipeline_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Load the Data
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# TODO: Load the housing data
df = pd.read_csv('/content/Housing.csv')

# TODO: How many houses are there?
print("Number of houses:", len(df))


# TODO: Show first 3 houses
print("First 3 houses:")
# Your code here
print(df.head(3))

Number of houses: 545
First 3 houses:
      price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no
1  12250000  8960         4          4        4      yes        no       no
2  12250000  9960         3          2        2      yes        no      yes

  hotwaterheating airconditioning  parking prefarea furnishingstatus
0              no             yes        2      yes        furnished
1              no             yes        3       no        furnished
2              no              no        2      yes   semi-furnished

In [4]:
# Look at Columns
# TODO: Show all column names
print("Columns:")
# Your code here
print(df.columns)

# TODO: Show data types of columns
print("Data types:")
print(df.dtypes)

Columns:
Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')
Data types:
price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder
#Convert Yes/No to 1/0
yes_no_columns=['mainroad',"guestroom","basement","hotwaterheating","airconditioning","parking","prefarea","furnishingstatus"]
df[yes_no_columns]=df[yes_no_columns].replace({"yes":1,"no":0})
print(df[yes_no_columns])

# Check what's in our data
print(df.head())

print("Current mainroad values:", df['mainroad'].head())
# Shows: yes, no, yes, yes, no
yes_no_cols=['mainroad',"guestroom","basement","hotwaterheating","airconditioning","parking","prefarea","furnishingstatus"]
for col in yes_no_cols:
    print(df[col].all)
# Models need numbers, not text!
print("_ _"*40)
le=LabelEncoder()
df['furnishingstatus']=le.fit_transform(df['furnishingstatus'])
print(df['furnishingstatus'].all)

# We need: yes → 1, no → 0
print(df.info)

     mainroad  guestroom  basement  hotwaterheating  airconditioning  parking  \
0           1          0         0                0                1        2
1           1          0         0                0                1        3
2           1          0         1                0                0        2
3           1          0         1                0                1        3
4           1          1         1                0                1        2
..        ...        ...       ...              ...              ...      ...
540         1          0         1                0                0        2
541         0          0         0                0                0        0
542         1          0         0                0                0        0
543         0          0         0                0                0        0
544         1          0         0                0                0        0

     prefarea  furnishingstatus
0           1                 0
1           0                 0
2           1                 1
3           1                 0
4           0                 0
..        ...               ...
540         0                 2
541         0                 1
542         0                 2
543         0                 0
544         0                 2

[545 rows x 8 columns]
      price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000  7420         4          2        3         1          0
1  12250000  8960         4          4        4         1          0
2  12250000  9960         3          2        2         1          0
3  12215000  7500         4          2        2         1          0
4  11410000  7420         4          1        2         1          1

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1
1         0                0                1        3         0
2         1                0                0        2         1
3         1                0                1        3         1
4         1                0                1        2         0

   furnishingstatus
0                 0
1                 0
2                 1
3                 0
4                 0
Current mainroad values: 0    1
1    1
2    1
3    1
4    1
Name: mainroad, dtype: int64
<bound method Series.all of 0      1
1      1
2      1
3      1
4      1
      ..
540    1
541    0
542    1
543    0
544    1
Name: mainroad, Length: 545, dtype: int64>
<bound method Series.all of 0      0
1      0
2      0
3      0
4      1
      ..
540    0
541    0
542    0
543    0
544    0
Name: guestroom, Length: 545, dtype: int64>
<bound method Series.all of 0      0
1      0
2      1
3      1
4      1
      ..
540    1
541    0
542    0
543    0
544    0
Name: basement, Length: 545, dtype: int64>
<bound method Series.all of 0      0
1      0
2      0
3      0
4      0
      ..
540    0
541    0
542    0
543    0
544    0
Name: hotwaterheating, Length: 545, dtype: int64>
<bound method Series.all of 0      1
1      1
2      0
3      1
4      1
      ..
540    0
541    0
542    0
543    0
544    0
Name: airconditioning, Length: 545, dtype: int64>
<bound method Series.all of 0      2
1      3
2      2
3      3
4      2
      ..
540    2
541    0
542    0
543    0
544    0
Name: parking, Length: 545, dtype: int64>
<bound method Series.all of 0      1
1      0
2      1
3      1
4      0
      ..
540    0
541    0
542    0
543    0
544    0
Name: prefarea, Length: 545, dtype: int64>
<bound method Series.all of 0      0
1      0
2      1
3      0
4      0
      ..
540    2
541    1
542    2
543    0
544    2
Name: furnishingstatus, Length: 545, dtype: int64>
_ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ _
<bound method Series.all of 0      0
1      0
2      1
3      0
4      0
      ..
540    2
541    1
542    2
543    0
544    2
Name: furnishingstatus, Length: 545, dtype: int64>
<bound method DataFrame.info of         price  area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0    13300000  7420         4          2        3         1          0
1    12250000  8960         4          4        4         1          0
2    12250000  9960         3          2        2         1          0
3    12215000  7500         4          2        2         1          0
4    11410000  7420         4          1        2         1          1
..        ...   ...       ...        ...      ...       ...        ...
540   1820000  3000         2          1        1         1          0
541   1767150  2400         3          1        1         0          0
542   1750000  3620         2          1        1         1          0
543   1750000  2910         3          1        1         0          0
544   1750000  3850         3          1        2         1          0

     basement  hotwaterheating  airconditioning  parking  prefarea  \
0           0                0                1        2         1
1           0                0                1        3         0
2           1                0                0        2         1
3           1                0                1        3         1
4           1                0                1        2         0
..        ...              ...              ...      ...       ...
540         1                0                0        2         0
541         0                0                0        0         0
542         0                0                0        0         0
543         0                0                0        0         0
544         0                0                0        0         0

     furnishingstatus
0                   0
1                   0
2                   1
3                   0
4                   0
..                ...
540                 2
541                 1
542                 2
543                 0
544                 2

[545 rows x 13 columns]>

In [9]:
# Split into Train and Test
df=df.drop('area',axis=1)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# Train-test split (80% train, 20% test)
train_size = int(0.8 * len(df))

train_df = df.iloc[:train_size]
test_df = df.iloc[train_size:]

print("Train Set:")
print(train_df)
print("\nTest Set:")
print(test_df)

# TODO: Split - 80% train, 20% test

Train Set:
       price  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
0    4060000         4          2        2         0          0         1
1    6650000         3          2        3         1          0         0
2    3710000         2          1        1         1          0         0
3    6440000         3          1        2         1          0         0
4    2800000         3          1        1         1          0         0
..       ...       ...        ...      ...       ...        ...       ...
431  5740000         3          1        3         1          0         0
432  7070000         4          2        2         1          0         0
433  5775000         3          2        4         1          0         0
434  5873000         3          1        3         1          1         0
435  2275000         1          1        1         0          0         0

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus
0                  0                0        1         0                 2
1                  0                1        0         1                 0
2                  0                0        0         0                 1
3                  0                1        0         0                 1
4                  0                0        0         0                 0
..               ...              ...      ...       ...               ...
431                0                1        0         0                 1
432                0                1        1         0                 0
433                0                1        0         0                 2
434                0                1        1         0                 0
435                0                0        0         0                 2

[436 rows x 12 columns]

Test Set:
       price  bedrooms  bathrooms  stories  mainroad  guestroom  basement  \
436  9870000         4          1        2         1          1         1
437  3990000         4          1        1         0          0         1
438  3850000         2          1        1         1          0         0
439  7000000         3          1        1         1          0         1
440  4200000         3          1        3         1          0         0
..       ...       ...        ...      ...       ...        ...       ...
540  6755000         4          2        4         1          0         0
541  6160000         4          2        1         1          0         1
542  4340000         3          2        3         1          0         0
543  3290000         2          1        1         1          0         0
544  6195000         3          2        4         1          1         0

     hotwaterheating  airconditioning  parking  prefarea  furnishingstatus
436                0                1        2         1                 0
437                0                0        0         0                 2
438                0                0        0         0                 1
439                0                1        1         1                 0
440                0                0        0         0                 1
..               ...              ...      ...       ...               ...
540                0                1        0         0                 2
541                0                1        0         1                 1
542                1                0        1         0                 0
543                0                0        0         0                 2
544                0                1        1         0                 1

[109 rows x 12 columns]

In [ ]:
#Apply StandardScaler
# Area is huge (1650-13300), Bedrooms is small (1-6)!
#Your Code here

In [ ]:
#train and test model
#your code here

In [ ]:
# Predict a House Price
# New house details:
# area=5000, bedrooms=3, bathrooms=2, stories=2,
# mainroad=yes, guestroom=no, basement=yes,
# hotwaterheating=no, airconditioning=yes,
# parking=2, prefarea=yes, furnishingstatus=furnished
#your code here